language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

services: mongodb

before_script: chmod 0777 ./node_modules/.bin/mocha

script:
  - npm test