language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

services: mongodb

before_script: 
  - chmod 0777 ./backend/node_modules/.bin/mocha

script:
  - cd backend/tests; npm test;
  - npm install -g serverless;
  - sls deploy;